# Generated by Django 5.0.1 on 2024-01-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityimage',
            field=models.ImageField(height_field='media/none', upload_to='media/none', verbose_name='Şehir Resmi', width_field='media/none'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='mainimg',
            field=models.ImageField(blank=True, upload_to='media/Anaresim', verbose_name='Anaresim'),
        ),
    ]
