# Generated by Django 5.0.1 on 2024-01-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0028_alter_city_cityimage_alter_hotel_mainimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityimage',
            field=models.ImageField(height_field='media/none', upload_to='none', verbose_name='Şehir Resmi', width_field='media/none'),
        ),
    ]
