# Generated by Django 5.0.1 on 2024-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_alter_city_cityimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityimage',
            field=models.ImageField(upload_to='media/none', verbose_name='Şehir Resmi'),
        ),
    ]
